# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{schema}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Kirsch"]
  s.date = %q{2010-12-01}
  s.description = %q{Deep type conversion through schemas for hashes}
  s.email = %q{danishkirel@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "autotest/discover.rb",
    "lib/schema.rb",
    "lib/schema/core_ext.rb",
    "lib/schema/include.rb",
    "lib/schema/schema.rb",
    "lib/schema/version.rb",
    "schema.gemspec",
    "spec/schema_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kirel/schema}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Schemas for hashes}
  s.test_files = [
    "spec/schema_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.2"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.2"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.2"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

